"""Check

Revision ID: 6e28e2670b50
Revises: 7a5284aa778d
Create Date: 2025-03-09 17:10:14.728066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e28e2670b50'
down_revision: Union[str, None] = '7a5284aa778d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_monitor_id'), 'monitor', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitor_id'), table_name='monitor')
    # ### end Alembic commands ###
