"""Check models

Revision ID: 7a5284aa778d
Revises: 245f8639b274
Create Date: 2025-03-09 11:59:26.463117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a5284aa778d'
down_revision: Union[str, None] = '245f8639b274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor', 'ssl_exp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor', sa.Column('ssl_exp', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
